### ISSUE TITLE
Error: Maximum allowed instances of a component reached.

### ISSUE THREAD

**Issue by sindhus-in** [wixplosives/codux-core#1024] opened 2024-02-03 10:13 UTC
<img width="1710" alt="image" src="https://github.com/wixplosives/codux-core/assets/85542169/a162b2ff-5be3-42b6-b52f-bd59b1a7c6e9">

I see this error when I run the git-ducks sample project. How can I fix it?

**Comment by tomrav** [comment] 2024-02-07 11:28
Sorry you've encountered this issue, we have identified the root cause (having to do with the Codux config), and this is resolved in our upcoming version.

Thank you for the report!

**Comment by tomrav** [comment] 2024-02-14 13:04
This issue has been resolved, you can grab the new version of Codux [here](https://www.codux.com/download).

**Closed by tomrav** 2024-02-14 13:04 UTC
